select * from Dim_Nps
select * from Dim_Localidade
select * from Dim_Segmento
select * from Dim_Faturamento
select * from Dim_Cliente
select * from Dim_Marca
select * from Dim_LinhaReceita
select * from Dim_Produto
select * from Dim_Modalidade
select * from Dim_StatusContrato
select * from Dim_Contrato
select * from Dim_Tempo
select * from Fato_Consumo